version: "3.9"

services:
  node-blue:
    build: .
    container_name: node-blue
    restart: always
    expose:
      - "3000"
    environment:
      - COLOR=blue
    networks:
      - web

  node-green:
    build: .
    container_name: node-green
    restart: always
    expose:
      - "3000"
    environment:
      - COLOR=green
    networks:
      - web

networks:
  web:
    external: true

